name: build
on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Install Dependencies'
      run: npm ci
    - name: 'Run Build'
      run: npm run build
